theme: jekyll-theme-minimal 
title: Ibai Irastorza Azcarate's CV ğŸ“œ
description: ğŸŒ± Basque ğŸ” in Berlin ğŸ™ 
logo: Me3_fixed_circle.png 
show_downloads: true
plugins:
  - jekyll-seo-tag # Add SEO plugin
google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  
email: batxes@gmail.com # Allow visitors to contact you
